### ISSUE TITLE
Error When Trying to Show Video

### ISSUE THREAD

**Issue by ernestoluciano** [mrf345/FQM#112]
ERROR [flask.app] Exception on /video [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/root/FQM/app/helpers.py", line 136, in decorated
    return function(*args, **kwargs)
  File "/root/FQM/app/views/customize.py", line 117, in video
    media_record = data.Media.get(form.video.data)
AttributeError: type object 'Media' has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/root/FQM/app/helpers.py", line 136, in decorated
    return function(*args, **kwargs)
  File "/root/FQM/app/views/customize.py", line 117, in video
    media_record = data.Media.get(form.video.data)
AttributeError: type object 'Media' has no attribute 'get'

**Comment by mrf345** [comment]
Hi @ernestoluciano , thanks for reporting #119 #118 #115 #112

I think I've passed some code refactoring in that part of the code-base yesterday, forgetting that it wasn't integration tested yet.

Sorry for the mess. I've added some tests and fixed them in https://github.com/mrf345/FQM/pull/120
Please let know if the mentioned issues still persist.
