### ISSUE TITLE
_sqlite3 

### ISSUE THREAD

**Issue by euro1nl** [mrf345/FQM#242]
**Describe the bug**
get multiple errors _sqlite

I run python3.7 run.py --cli

**Please complete the following information:**
 - Operating System (OS): lentos 8
 - Browser Chrome 
 - FQM Version 0,9

**Error:**
```log
[root@qtc01 01]# python3.7  run.py --cli --ip 185.107.68.17 --poort 1001
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app.cli import interface
  File "/root/qtc/01/app/__init__.py", line 9, in <module>
    'GUNICORN': 'gunicorn' in os.environ.get('SERVER_SOFTWARE', '')})  # noqa
  File "/root/qtc/01/app/main.py", line 113, in bundle_app
    create_db(app)
  File "/root/qtc/01/app/main.py", line 97, in create_db
    db.create_all()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 556, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 972, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 488, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 430, in dbapi
    from sqlite3 import dbapi2 as sqlite
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by euro1nl** [comment]
solved, new install
