### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Husam1990** [mrf345/FQM#276]
Hello Mohmmad
Greetings

I install system on fresh window 10 and add 9 branches , but its very slow and page take a time to reload ! 
I checked recourse (Memory , HDD, CPU .. ) its normal and within range !

when page stuck , footer related that page try connect reddit.com !!!

how can I check root causes of this problem !?

BR

**Comment by Husam1990** [comment]
jquery.min.js:4          GET http://192.168.1.122:5000/repeat_announcement net::ERR_INSUFFICIENT_RESOURCES
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.<computed> @ jquery.min.js:4
(anonymous) @ display:5
setInterval (async)
(anonymous) @ display:5
jsonstream.min.js:202 Uncaught Error: json_stream() cannot reach to the server !
    at Object.error (jsonstream.min.js:202:31583)
    at l (jsonstream.min.js:25:24024)
    at Object.fireWith [as rejectWith] (jsonstream.min.js:25:24772)
    at D (jsonstream.min.js:25:75223)
    at XMLHttpRequest.<anonymous> (jsonstream.min.js:25:77513)
error @ jsonstream.min.js:202
l @ jsonstream.min.js:25
fireWith @ jsonstream.min.js:25
D @ jsonstream.min.js:25
(anonymous) @ jsonstream.min.js:25
error (async)
send @ jsonstream.min.js:25
ajax @ jsonstream.min.js:25
k.each.k.<computed> @ jsonstream.min.js:25
getJSON @ jsonstream.min.js:25
(anonymous) @ jsonstream.min.js:202
setInterval (async)
(anonymous) @ jsonstream.min.js:202
l @ jsonstream.min.js:202
(anonymous) @ display:5
jsonstream.min.js:25          GET http://192.168.1.122:5000/feed net::ERR_INSUFFICIENT_RESOURCES
send @ jsonstream.min.js:25
ajax @ jsonstream.min.js:25
k.each.k.<computed> @ jsonstream.min.js:25
getJSON @ jsonstream.min.js:25
(anonymous) @ jsonstream.min.js:202
setInterval (async)
(anonymous) @ jsonstream.min.js:202
l @ jsonstream.min.js:202
(anonymous) @ display:5
display:5 {readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
