### ISSUE TITLE
Display screen is not update waiting ticket

### ISSUE THREAD

**Issue by basit-Ali1122** [mrf345/FQM#93]
when i generate ticket from printer by clicking task on touch screen my display screen is not update and console generate this error again and again 

Traceback (most recent call last):
  File "C:\Users\Basit\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Basit\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Basit\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Basit\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Basit\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Basit\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Basit\Downloads\FQM-master\app\views\core.py", line 340, in feed
    ) if current_ticket else empty_text
AttributeError: 'Serial' object has no attribute 'ticket'

**Comment by Edi672** [comment]
i have the same problem as yours, what have you done to solve it?
